### ISSUE TITLE
软件添加请求

### ISSUE THREAD

**Issue by Bryan2333** [Morton-L/BoltWrt#1]
可否在默认的软件源中添加Smartdns和Vlmcsd？

**Comment by Morton-Li** [comment]
您好，我会考虑将SmartDNS加入软件源中，只是默认软件源中已有两个与SmartDNS类似功能的组件，且其中一款已编译进正式版固件中，请问SmartDNS与自带的两款组件相比，有更好的表现吗？关于Vlmcsd组件我一直在考虑是否要加入软件源中，因为我曾收到过微软的投诉，既然用户有需求，我觉得它会在下次更新中出现，感谢您的关注。

**Comment by Bryan2333** [comment]
我个人没有测试过Smartdns和其他两款组件哪个有更好的表现。我只是觉得如果将SmartDNS添加到软件源的话，用户会有更多的选择。

**Comment by Morton-Li** [comment]
考虑到SmartDNS对DNS查询效率的提升,如若稳定性测试通过,该软件将在下一个版本中默认集成.

**Comment by Bryan2333** [comment]
OK
